<a href="https://colab.research.google.com/github/vipin-jangra/machine_leaning/blob/main/KNN_car_suv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
dataset = pd.read_csv('suv_data.csv')

In [58]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [59]:
X = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:,4].values

In [60]:
#splitting the datset into test and training 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((280, 2), (120, 2), (280,), (120,))

In [61]:
#feature scalling
# from sklearn import preprocessing
# min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
# X_train = min_max_scaler.fit_transform(X_train)
# X_test = min_max_scaler.transform(X_test)

In [62]:
#feature sclling standard
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test =sc.transform(X_test)

In [63]:
X_train,X_test

(array([[-1.1631724 , -1.5849703 ],
        [ 2.17018137,  0.93098672],
        [ 0.0133054 ,  1.22017719],
        [ 0.20938504,  1.07558195],
        [ 0.40546467, -0.48604654],
        [-0.28081405, -0.31253226],
        [ 0.99370357, -0.8330751 ],
        [ 0.99370357,  1.8563962 ],
        [ 0.0133054 ,  1.24909623],
        [-0.86905295,  2.26126285],
        [-1.1631724 , -1.5849703 ],
        [ 2.17018137, -0.80415605],
        [-1.35925203, -1.46929411],
        [ 0.40546467,  2.2901819 ],
        [ 0.79762394,  0.75747245],
        [-0.96709276, -0.31253226],
        [ 0.11134522,  0.75747245],
        [-0.96709276,  0.55503912],
        [ 0.30742485,  0.06341534],
        [ 0.69958412, -1.26686079],
        [-0.47689368, -0.0233418 ],
        [-1.7514113 ,  0.3526058 ],
        [-0.67297331,  0.12125343],
        [ 0.40546467,  0.29476771],
        [-0.28081405,  0.06341534],
        [-0.47689368,  2.2901819 ],
        [ 0.20938504,  0.03449629],
        [ 1.28782302,  2.203

In [64]:
#fitting knn 
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3,metric='minkowski',p=2)
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [65]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0])

In [66]:
#creating the confusion metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[73,  6],
       [ 5, 36]])